# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupList',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=32)),
                ('ipaddress', models.GenericIPAddressField(protocol='ipv4')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.GroupList')),
            ],
        ),
    ]
